module.exports = {
  AUTH_SERVICE: process.env.AUTH_SERVICE,
  PROPERTY_SERVICE: process.env.PROPERTY_SERVICE,
  BOOKING_SERVICE: process.env.BOOKING_SERVICE,
  PAYMENT_SERVICE: process.env.PAYMENT_SERVICE,
  NOTIFICATION_SERVICE: process.env.NOTIFICATION_SERVICE
};